package dev.sk2andy.materialbrowser.shared.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val CandyLightColors = lightColorScheme(
    primary = Color(0xFF6548C5),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE8DEFF),
    onPrimaryContainer = Color(0xFF21005D),
    secondary = Color(0xFFA9004B),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFD9E2),
    onSecondaryContainer = Color(0xFF3F0018),
    tertiary = Color(0xFF7D5260),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFFD9E3),
    onTertiaryContainer = Color(0xFF31101D),
    surface = Color(0xFFFFF8FB),
    surfaceDim = Color(0xFFE1D8DD),
    surfaceBright = Color(0xFFFFF8FB),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFFCF0F6),
    surfaceContainer = Color(0xFFF6EDF2),
    surfaceContainerHigh = Color(0xFFF0E7EC),
    surfaceContainerHighest = Color(0xFFEAE1E6),
)

val CandyDarkColors = darkColorScheme(
    primary = Color(0xFFCFBDFF),
    onPrimary = Color(0xFF35206F),
    primaryContainer = Color(0xFF4C3795),
    onPrimaryContainer = Color(0xFFE8DEFF),
    secondary = Color(0xFFFFB1C8),
    onSecondary = Color(0xFF65002A),
    secondaryContainer = Color(0xFF88003D),
    onSecondaryContainer = Color(0xFFFFD9E2),
    tertiary = Color(0xFFEFB8C8),
    onTertiary = Color(0xFF492532),
    tertiaryContainer = Color(0xFF633B48),
    onTertiaryContainer = Color(0xFFFFD9E3),
    surface = Color(0xFF171216),
    surfaceDim = Color(0xFF171216),
    surfaceBright = Color(0xFF3E373C),
    surfaceContainerLowest = Color(0xFF110D10),
    surfaceContainerLow = Color(0xFF20191D),
    surfaceContainer = Color(0xFF251E23),
    surfaceContainerHigh = Color(0xFF30282D),
    surfaceContainerHighest = Color(0xFF3B3338),
)

val NeutralLightColors = lightColorScheme(
    primary = Color(0xFF4D5D62),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD0E6EC),
    onPrimaryContainer = Color(0xFF081F24),
    secondary = Color(0xFF586064),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFDCE4E7),
    onSecondaryContainer = Color(0xFF171C1E),
    tertiary = Color(0xFF5D5F6B),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE1E2EF),
    onTertiaryContainer = Color(0xFF191A24),
    surface = Color(0xFFFAF9F7),
    surfaceDim = Color(0xFFDBDAD8),
    surfaceBright = Color(0xFFFAF9F7),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF5F4F2),
    surfaceContainer = Color(0xFFEFEEEC),
    surfaceContainerHigh = Color(0xFFE9E8E6),
    surfaceContainerHighest = Color(0xFFE3E2E0),
    surfaceVariant = Color(0xFFDFE3E4),
    onSurfaceVariant = Color(0xFF41484B),
    outline = Color(0xFF71787B),
    outlineVariant = Color(0xFFC1C7C9),
    inverseSurface = Color(0xFF303132),
    inverseOnSurface = Color(0xFFF1F0EE),
    inversePrimary = Color(0xFFB4CBD1),
)

val NeutralDarkColors = darkColorScheme(
    primary = Color(0xFFB4CBD1),
    onPrimary = Color(0xFF1F3439),
    primaryContainer = Color(0xFF354A4F),
    onPrimaryContainer = Color(0xFFD0E6EC),
    secondary = Color(0xFFC0C8CB),
    onSecondary = Color(0xFF2A3134),
    secondaryContainer = Color(0xFF41484B),
    onSecondaryContainer = Color(0xFFDCE4E7),
    tertiary = Color(0xFFC5C6D4),
    onTertiary = Color(0xFF2E303B),
    tertiaryContainer = Color(0xFF454751),
    onTertiaryContainer = Color(0xFFE1E2EF),
    surface = Color(0xFF121415),
    surfaceDim = Color(0xFF121415),
    surfaceBright = Color(0xFF383A3B),
    surfaceContainerLowest = Color(0xFF0D0F10),
    surfaceContainerLow = Color(0xFF1A1C1D),
    surfaceContainer = Color(0xFF1E2021),
    surfaceContainerHigh = Color(0xFF292A2B),
    surfaceContainerHighest = Color(0xFF343536),
    surfaceVariant = Color(0xFF41484B),
    onSurfaceVariant = Color(0xFFC1C7C9),
    outline = Color(0xFF8B9295),
    outlineVariant = Color(0xFF41484B),
    inverseSurface = Color(0xFFE3E2E0),
    inverseOnSurface = Color(0xFF2F3031),
    inversePrimary = Color(0xFF4D5D62),
)
